# Generated by Django 6.0.4 on 2026-04-28 09:06

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('electeur', 'Electeur')], default='electeur', max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('id_electeur', models.BooleanField(default=False)),
                ('id_candidat', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('nom_elec', models.CharField(max_length=100, verbose_name="Nom de l'électeur")),
                ('prenom_elec', models.CharField(max_length=100, verbose_name="Prénom de l'électeur")),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('a_deja_vote', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Electeur',
                'verbose_name_plural': 'Electeurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scrutin',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('annule', 'Annulé')], default='ouvert', max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Scrutin',
                'verbose_name_plural': 'Scrutins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_admin', models.CharField(max_length=100, verbose_name="Nom de l'administrateur")),
                ('prenom_admin', models.CharField(max_length=100, verbose_name="Prénom de l'administrateur")),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'managed': True,
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Logaudit',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logaudit',
                'verbose_name_plural': 'Logaudits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du candidat')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom du candidat')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/')),
                ('matricule', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('nb_vote', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='users.scrutin')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.candidat')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.electeur')),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.scrutin')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='scrutin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrutins', to='users.administrateur'),
        ),
        migrations.CreateModel(
            name='DemandeCandidature',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biographie', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='demandes/')),
                ('age', models.IntegerField()),
                ('matricule', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='users.scrutin')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.administrateur')),
            ],
            options={
                'verbose_name': 'DemandeCandidature',
                'verbose_name_plural': 'DemandeCandidatures',
                'managed': True,
            },
        ),
    ]
