# Generated by Django 6.0.4 on 2026-05-05 05:24

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='demandecandidature',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='demandecandidature',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='electeur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='electeur',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='logaudit',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='logaudit',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='scrutin',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='scrutin',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id_candidat',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id_electeur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='candidat',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='electeur',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electeur',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='electeur',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logaudit',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrutin',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='vote',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('electeur', 'Electeur')], default='electeur', max_length=20),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='utilisateur_email_1cb90f_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['matricule'], name='utilisateur_matricu_0b87e1_idx'),
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateurs',
        ),
    ]
