# Generated by Django 6.0.4 on 2026-05-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecandidature',
            name='scrutin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_candidature', to='users.scrutin'),
        ),
    ]
