# Generated by Django 6.0.4 on 2026-05-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_demandecandidature_scrutin'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeelecteur',
            name='scrutin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_electeur', to='users.scrutin'),
        ),
    ]
