# Generated by Django 6.0.4 on 2026-05-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_scrutin_to_demandeelecteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeelecteur',
            name='scrutin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_electeur', to='users.scrutin'),
        ),
    ]
