# Generated by Django 6.0.4 on 2026-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_make_scrutin_required_in_demandeelecteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecandidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='demandeelecteur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrutin',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('en attente', 'En attente')], default='ouvert', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('ELECTEUR', 'Électeur'), ('CANDIDAT', 'Candidat')], default='ELECTEUR', max_length=20),
        ),
    ]
