# Generated by Django 6.0.4 on 2026-05-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_demandecandidature_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='scrutin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electeurs', to='users.scrutin'),
        ),
    ]
