# Generated by Django 6.0.4 on 2026-05-27 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidat_scrutin_electeur_scrutin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='scrutin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='users.scrutin'),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='scrutin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electeurs', to='users.scrutin'),
        ),
    ]
