# Generated by Django 6.0.4 on 2026-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_candidat_scrutin_alter_electeur_scrutin'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecandidature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidatures/'),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='programme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecandidature',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
