# Generated by Django 6.0.4 on 2026-05-30 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_electeur_notification_ouverture_envoyee'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutin',
            name='date_debut_vote',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 0, 10, 8, 281609, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrutin',
            name='date_fin_vote',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 0, 10, 36, 443230, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrutin',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_vote', 'En vote'), ('ferme', 'Fermé'), ('annule', 'Annulé')], default='ouvert', max_length=50),
        ),
    ]
